import random

def roll_dice():
    return random.randint(1, 6)

def play_snake_and_ladder(num_players):
    players = [0] * num_players
    while True:
        for i in range(num_players):
            print(f"Player {i+1}'s turn:")
            roll = roll_dice()
            print(f"Rolled: {roll}")
            players[i] += roll
            if players[i] > 100:
                players[i] -= roll
            if players[i] in snakes:
                print(f"Bitten by a snake! Moving to square {snakes[players[i]]}")
                players[i] = snakes[players[i]]
            elif players[i] in ladders:
                print(f"Climbing a ladder! Moving to square {ladders[players[i]]}")
                players[i] = ladders[players[i]]
            print(f"Player {i+1} is now on square {players[i]}\n")
            if players[i] == 100:
                print(f"Player {i+1} wins!")
                return

# Define snake and ladder positions
snakes = {17: 7, 54: 35, 62: 19, 98: 61}
ladders = {3: 21, 11: 42, 40: 67, 71: 92}

num_players = int(input("Enter the number of players: "))
play_snake_and_ladder(num_players)




























































































